default_context:
    project_name: "application_properties"
    project_version: "0.8.3"
    project_src_additional_path: "" # , stubs
    project_src_dependencies: "tomli, types-PyYAML"
    pypi_package_name: "application_properties"
    github_organization: "jackdewinter"
    github_project_name: "application_properties"
    one_line_setup_description : "A simple, easy to use, unified manner of accessing program properties."
    setup_development_status" : "4 - Beta"
    setup_intended_audience : "\"Intended Audience :: Developers\","
    setup_additional_classifier : "\"Topic :: Software Development :: Libraries :: Application Frameworks\","
    setup_keywords : "\"properties\""
    setup_package_modules : "\"application_properties\""
    setup_package_data : "\"\": [\"*.typed\"]"
    rtd_site_name : "Application Properties"
    rtd_deploy_name : "application_properties"
    pipfile_additional_packages: "pyyaml = \">=5.4.1\",tomli = \">=2.0.1\""
    install_requirements_additional_packages: "tomli>=2.0.1,pyyaml>=5.4.1"